-- Compact Restaurant POS setup. Paste the WHOLE file into Supabase SQL Editor and run once.

create extension if not exists "pgcrypto";
create sequence if not exists public.order_bill_sequence;

create table if not exists public.restaurants (id uuid primary key default gen_random_uuid(), name text not null, slug text not null unique, address text, phone text, currency text not null default '$', tax_rate numeric(6,3) not null default 10, created_at timestamptz not null default now());
create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, restaurant_id uuid not null references public.restaurants(id) on delete cascade, full_name text not null, role text not null check (role in ('owner','manager','cashier')), created_at timestamptz not null default now());
create table if not exists public.menu_categories (id uuid primary key default gen_random_uuid(), restaurant_id uuid not null references public.restaurants(id) on delete cascade, name text not null, sort_order integer not null default 0, created_at timestamptz not null default now());
create table if not exists public.menu_items (id uuid primary key default gen_random_uuid(), restaurant_id uuid not null references public.restaurants(id) on delete cascade, category_id uuid not null references public.menu_categories(id) on delete restrict, name text not null, description text, price numeric(12,2) not null check (price >= 0), is_active boolean not null default true, prep_minutes integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.inventory_items (id uuid primary key default gen_random_uuid(), restaurant_id uuid not null references public.restaurants(id) on delete cascade, name text not null, unit text not null, quantity_on_hand numeric(14,4) not null default 0 check (quantity_on_hand >= 0), reorder_level numeric(14,4) not null default 0, cost_per_unit numeric(12,4) not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.menu_item_ingredients (id uuid primary key default gen_random_uuid(), restaurant_id uuid not null references public.restaurants(id) on delete cascade, menu_item_id uuid not null references public.menu_items(id) on delete cascade, inventory_item_id uuid not null references public.inventory_items(id) on delete restrict, quantity numeric(14,4) not null check (quantity > 0), unit text not null, created_at timestamptz not null default now(), unique (restaurant_id, menu_item_id, inventory_item_id));
create table if not exists public.orders (id uuid primary key default gen_random_uuid(), restaurant_id uuid not null references public.restaurants(id) on delete cascade, bill_number text not null, cashier_id uuid not null references public.profiles(id) on delete restrict, status text not null default 'paid' check (status in ('open','paid','void')), subtotal numeric(12,2) not null default 0, discount numeric(12,2) not null default 0, tax numeric(12,2) not null default 0, total numeric(12,2) not null default 0, created_at timestamptz not null default now(), unique (restaurant_id, bill_number));
create table if not exists public.order_items (id uuid primary key default gen_random_uuid(), restaurant_id uuid not null references public.restaurants(id) on delete cascade, order_id uuid not null references public.orders(id) on delete cascade, menu_item_id uuid not null references public.menu_items(id) on delete restrict, item_name text not null, unit_price numeric(12,2) not null, quantity integer not null check (quantity > 0), line_total numeric(12,2) not null, note text, created_at timestamptz not null default now());
create table if not exists public.payments (id uuid primary key default gen_random_uuid(), restaurant_id uuid not null references public.restaurants(id) on delete cascade, order_id uuid not null references public.orders(id) on delete cascade, method text not null check (method in ('cash','card','upi','split')), amount numeric(12,2) not null check (amount >= 0), created_at timestamptz not null default now());
create table if not exists public.inventory_movements (id uuid primary key default gen_random_uuid(), restaurant_id uuid not null references public.restaurants(id) on delete cascade, inventory_item_id uuid not null references public.inventory_items(id) on delete restrict, order_id uuid references public.orders(id) on delete set null, movement_type text not null check (movement_type in ('sale_deduction','manual_adjustment','purchase')), quantity_delta numeric(14,4) not null, quantity_after numeric(14,4) not null, note text, created_by uuid references public.profiles(id) on delete set null, created_at timestamptz not null default now());
create table if not exists public.daily_sales_summary (id uuid primary key default gen_random_uuid(), restaurant_id uuid not null references public.restaurants(id) on delete cascade, sales_date date not null, order_count integer not null default 0, gross_sales numeric(12,2) not null default 0, discount_total numeric(12,2) not null default 0, tax_total numeric(12,2) not null default 0, net_sales numeric(12,2) not null default 0, updated_at timestamptz not null default now(), unique (restaurant_id, sales_date));
create table if not exists public.staff_invites (id uuid primary key default gen_random_uuid(), restaurant_id uuid not null references public.restaurants(id) on delete cascade, email text not null, role text not null check (role in ('manager','cashier')), invited_by uuid references public.profiles(id) on delete set null, accepted_at timestamptz, created_at timestamptz not null default now());
create table if not exists public.restaurant_settings (id uuid primary key default gen_random_uuid(), restaurant_id uuid not null unique references public.restaurants(id) on delete cascade, bill_prefix text not null default 'TS', receipt_footer text not null default 'Thank you for dining with us.', print_kitchen_copy boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());

create index if not exists idx_profiles_restaurant_id on public.profiles(restaurant_id);
create index if not exists idx_menu_items_restaurant_id on public.menu_items(restaurant_id);
create index if not exists idx_inventory_items_restaurant_id on public.inventory_items(restaurant_id);
create index if not exists idx_orders_restaurant_created on public.orders(restaurant_id, created_at desc);
create index if not exists idx_order_items_order_id on public.order_items(order_id);
create index if not exists idx_inventory_movements_restaurant_item on public.inventory_movements(restaurant_id, inventory_item_id, created_at desc);

create or replace function public.touch_updated_at() returns trigger language plpgsql as $touch_updated_at$ begin new.updated_at = now(); return new; end; $touch_updated_at$;
drop trigger if exists touch_menu_items_updated_at on public.menu_items;
create trigger touch_menu_items_updated_at before update on public.menu_items for each row execute function public.touch_updated_at();
drop trigger if exists touch_inventory_items_updated_at on public.inventory_items;
create trigger touch_inventory_items_updated_at before update on public.inventory_items for each row execute function public.touch_updated_at();
drop trigger if exists touch_restaurant_settings_updated_at on public.restaurant_settings;
create trigger touch_restaurant_settings_updated_at before update on public.restaurant_settings for each row execute function public.touch_updated_at();

drop function if exists public.create_order_with_inventory_deduction(uuid, uuid, text, numeric, numeric, jsonb);
create or replace function public.create_order_with_inventory_deduction(p_restaurant_id uuid, p_cashier_id uuid, p_payment_method text, p_discount numeric, p_tax numeric, p_items jsonb) returns table(order_id uuid, bill_number text) language plpgsql security definer set search_path = public as $create_order_with_inventory_deduction$
declare v_order_id uuid; v_bill_number text; v_subtotal numeric(12,2) := 0; v_discount numeric(12,2) := coalesce(p_discount, 0); v_tax numeric(12,2) := coalesce(p_tax, 0); v_total numeric(12,2); v_item jsonb; v_menu_item_id uuid; v_menu_item_name text; v_menu_item_price numeric(12,2); v_quantity integer; v_note text; v_required record; v_inventory record; v_sales_date date := current_date; v_cashier_role text; v_requester_role text;
begin
  if p_payment_method not in ('cash','card','upi','split') then raise exception 'Invalid payment method: %', p_payment_method; end if;
  if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then raise exception 'Order must contain at least one item'; end if;
  select p.role into v_cashier_role from public.profiles p where p.id = p_cashier_id and p.restaurant_id = p_restaurant_id;
  if v_cashier_role is null or v_cashier_role not in ('owner','manager','cashier') then raise exception 'Cashier is not allowed to create orders for this restaurant'; end if;
  select p.role into v_requester_role from public.profiles p where p.id = auth.uid() and p.restaurant_id = p_restaurant_id;
  if v_requester_role is null or v_requester_role not in ('owner','manager','cashier') then raise exception 'Current user is not allowed to create orders for this restaurant'; end if;
  for v_item in select * from jsonb_array_elements(p_items) loop
    v_quantity := coalesce((v_item->>'quantity')::integer, 0);
    if v_quantity <= 0 then raise exception 'Order item quantity must be greater than zero'; end if;
    select mi.id, mi.name, mi.price into v_menu_item_id, v_menu_item_name, v_menu_item_price from public.menu_items mi where mi.id = (v_item->>'menu_item_id')::uuid and mi.restaurant_id = p_restaurant_id and mi.is_active = true;
    if not found then raise exception 'Menu item % is not available', v_item->>'menu_item_id'; end if;
    v_subtotal := v_subtotal + (v_menu_item_price * v_quantity);
  end loop;
  v_total := greatest(v_subtotal - v_discount, 0) + v_tax;
  v_bill_number := concat(coalesce((select rs.bill_prefix from public.restaurant_settings rs where rs.restaurant_id = p_restaurant_id), 'TS'), '-', to_char(now(), 'YYYYMMDD'), '-', lpad(nextval('public.order_bill_sequence')::text, 5, '0'));
  insert into public.orders (restaurant_id, bill_number, cashier_id, status, subtotal, discount, tax, total) values (p_restaurant_id, v_bill_number, p_cashier_id, 'paid', v_subtotal, v_discount, v_tax, v_total) returning id into v_order_id;
  for v_item in select * from jsonb_array_elements(p_items) loop
    v_quantity := (v_item->>'quantity')::integer; v_note := nullif(v_item->>'note', '');
    select mi.id, mi.name, mi.price into v_menu_item_id, v_menu_item_name, v_menu_item_price from public.menu_items mi where mi.id = (v_item->>'menu_item_id')::uuid and mi.restaurant_id = p_restaurant_id and mi.is_active = true;
    insert into public.order_items (restaurant_id, order_id, menu_item_id, item_name, unit_price, quantity, line_total, note) values (p_restaurant_id, v_order_id, v_menu_item_id, v_menu_item_name, v_menu_item_price, v_quantity, v_menu_item_price * v_quantity, v_note);
  end loop;
  for v_required in select mii.inventory_item_id, sum(mii.quantity * ((item.value->>'quantity')::integer)) as required_quantity from jsonb_array_elements(p_items) as item(value) join public.menu_item_ingredients mii on mii.menu_item_id = (item.value->>'menu_item_id')::uuid and mii.restaurant_id = p_restaurant_id group by mii.inventory_item_id loop
    select ii.id, ii.quantity_on_hand, ii.name into v_inventory from public.inventory_items ii where ii.id = v_required.inventory_item_id and ii.restaurant_id = p_restaurant_id for update;
    if not found then raise exception 'Inventory item % not found', v_required.inventory_item_id; end if;
    if v_inventory.quantity_on_hand < v_required.required_quantity then raise exception 'Insufficient stock for %. Required %, available %', v_inventory.name, v_required.required_quantity, v_inventory.quantity_on_hand; end if;
    update public.inventory_items set quantity_on_hand = quantity_on_hand - v_required.required_quantity where id = v_required.inventory_item_id and restaurant_id = p_restaurant_id returning quantity_on_hand into v_inventory.quantity_on_hand;
    insert into public.inventory_movements (restaurant_id, inventory_item_id, order_id, movement_type, quantity_delta, quantity_after, note, created_by) values (p_restaurant_id, v_required.inventory_item_id, v_order_id, 'sale_deduction', -v_required.required_quantity, v_inventory.quantity_on_hand, concat('Auto deduction for bill ', v_bill_number), p_cashier_id);
  end loop;
  insert into public.payments (restaurant_id, order_id, method, amount) values (p_restaurant_id, v_order_id, p_payment_method, v_total);
  insert into public.daily_sales_summary (restaurant_id, sales_date, order_count, gross_sales, discount_total, tax_total, net_sales) values (p_restaurant_id, v_sales_date, 1, v_subtotal, v_discount, v_tax, v_total) on conflict (restaurant_id, sales_date) do update set order_count = public.daily_sales_summary.order_count + 1, gross_sales = public.daily_sales_summary.gross_sales + excluded.gross_sales, discount_total = public.daily_sales_summary.discount_total + excluded.discount_total, tax_total = public.daily_sales_summary.tax_total + excluded.tax_total, net_sales = public.daily_sales_summary.net_sales + excluded.net_sales, updated_at = now();
  order_id := v_order_id; bill_number := v_bill_number; return next;
end;
$create_order_with_inventory_deduction$;
grant execute on function public.create_order_with_inventory_deduction(uuid, uuid, text, numeric, numeric, jsonb) to authenticated;

alter table public.restaurants enable row level security; alter table public.profiles enable row level security; alter table public.menu_categories enable row level security; alter table public.menu_items enable row level security; alter table public.inventory_items enable row level security; alter table public.menu_item_ingredients enable row level security; alter table public.orders enable row level security; alter table public.order_items enable row level security; alter table public.payments enable row level security; alter table public.inventory_movements enable row level security; alter table public.daily_sales_summary enable row level security; alter table public.staff_invites enable row level security; alter table public.restaurant_settings enable row level security;

do $drop_old_policies$ declare policy_record record; begin for policy_record in select schemaname, tablename, policyname from pg_policies where schemaname = 'public' and tablename in ('restaurants','profiles','menu_categories','menu_items','inventory_items','menu_item_ingredients','orders','order_items','payments','inventory_movements','daily_sales_summary','staff_invites','restaurant_settings') loop execute format('drop policy if exists %I on %I.%I', policy_record.policyname, policy_record.schemaname, policy_record.tablename); end loop; end; $drop_old_policies$;

create or replace function public.current_profile_restaurant_id() returns uuid language sql stable security definer set search_path = public as $current_profile_restaurant_id$ select p.restaurant_id from public.profiles p where p.id = auth.uid() $current_profile_restaurant_id$;
create or replace function public.current_profile_role() returns text language sql stable security definer set search_path = public as $current_profile_role$ select p.role from public.profiles p where p.id = auth.uid() $current_profile_role$;
create or replace function public.has_role(required_roles text[]) returns boolean language sql stable security definer set search_path = public as $has_role$ select coalesce(public.current_profile_role() = any(required_roles), false) $has_role$;
create or replace function public.same_restaurant(target_restaurant_id uuid) returns boolean language sql stable security definer set search_path = public as $same_restaurant$ select coalesce(public.current_profile_restaurant_id() = target_restaurant_id, false) $same_restaurant$;

create policy "restaurants_select_members" on public.restaurants for select using (public.same_restaurant(id));
create policy "restaurants_update_owner" on public.restaurants for update using (public.same_restaurant(id) and public.has_role(array['owner'])) with check (public.same_restaurant(id) and public.has_role(array['owner']));
create policy "profiles_select_members" on public.profiles for select using (public.same_restaurant(restaurant_id));
create policy "profiles_insert_owner" on public.profiles for insert with check (public.same_restaurant(restaurant_id) and public.has_role(array['owner']));
create policy "profiles_update_owner" on public.profiles for update using (public.same_restaurant(restaurant_id) and public.has_role(array['owner'])) with check (public.same_restaurant(restaurant_id) and public.has_role(array['owner']));
create policy "profiles_delete_owner" on public.profiles for delete using (public.same_restaurant(restaurant_id) and public.has_role(array['owner']));
create policy "menu_categories_select_members" on public.menu_categories for select using (public.same_restaurant(restaurant_id));
create policy "menu_categories_insert_manager" on public.menu_categories for insert with check (public.same_restaurant(restaurant_id) and public.has_role(array['owner','manager']));
create policy "menu_categories_update_manager" on public.menu_categories for update using (public.same_restaurant(restaurant_id) and public.has_role(array['owner','manager'])) with check (public.same_restaurant(restaurant_id) and public.has_role(array['owner','manager']));
create policy "menu_categories_delete_manager" on public.menu_categories for delete using (public.same_restaurant(restaurant_id) and public.has_role(array['owner','manager']));
create policy "menu_items_select_members" on public.menu_items for select using (public.same_restaurant(restaurant_id));
create policy "menu_items_insert_manager" on public.menu_items for insert with check (public.same_restaurant(restaurant_id) and public.has_role(array['owner','manager']));
create policy "menu_items_update_manager" on public.menu_items for update using (public.same_restaurant(restaurant_id) and public.has_role(array['owner','manager'])) with check (public.same_restaurant(restaurant_id) and public.has_role(array['owner','manager']));
create policy "menu_items_delete_manager" on public.menu_items for delete using (public.same_restaurant(restaurant_id) and public.has_role(array['owner','manager']));
create policy "inventory_items_select_manager" on public.inventory_items for select using (public.same_restaurant(restaurant_id) and public.has_role(array['owner','manager']));
create policy "inventory_items_insert_manager" on public.inventory_items for insert with check (public.same_restaurant(restaurant_id) and public.has_role(array['owner','manager']));
create policy "inventory_items_update_manager" on public.inventory_items for update using (public.same_restaurant(restaurant_id) and public.has_role(array['owner','manager'])) with check (public.same_restaurant(restaurant_id) and public.has_role(array['owner','manager']));
create policy "inventory_items_delete_manager" on public.inventory_items for delete using (public.same_restaurant(restaurant_id) and public.has_role(array['owner','manager']));
create policy "menu_item_ingredients_select_manager" on public.menu_item_ingredients for select using (public.same_restaurant(restaurant_id) and public.has_role(array['owner','manager']));
create policy "menu_item_ingredients_insert_manager" on public.menu_item_ingredients for insert with check (public.same_restaurant(restaurant_id) and public.has_role(array['owner','manager']));
create policy "menu_item_ingredients_update_manager" on public.menu_item_ingredients for update using (public.same_restaurant(restaurant_id) and public.has_role(array['owner','manager'])) with check (public.same_restaurant(restaurant_id) and public.has_role(array['owner','manager']));
create policy "menu_item_ingredients_delete_manager" on public.menu_item_ingredients for delete using (public.same_restaurant(restaurant_id) and public.has_role(array['owner','manager']));
create policy "orders_select_members" on public.orders for select using (public.same_restaurant(restaurant_id));
create policy "order_items_select_members" on public.order_items for select using (public.same_restaurant(restaurant_id));
create policy "payments_select_members" on public.payments for select using (public.same_restaurant(restaurant_id));
create policy "inventory_movements_select_manager" on public.inventory_movements for select using (public.same_restaurant(restaurant_id) and public.has_role(array['owner','manager']));
create policy "daily_sales_summary_select_manager" on public.daily_sales_summary for select using (public.same_restaurant(restaurant_id) and public.has_role(array['owner','manager']));
create policy "staff_invites_select_owner" on public.staff_invites for select using (public.same_restaurant(restaurant_id) and public.has_role(array['owner']));
create policy "staff_invites_insert_owner" on public.staff_invites for insert with check (public.same_restaurant(restaurant_id) and public.has_role(array['owner']));
create policy "staff_invites_update_owner" on public.staff_invites for update using (public.same_restaurant(restaurant_id) and public.has_role(array['owner'])) with check (public.same_restaurant(restaurant_id) and public.has_role(array['owner']));
create policy "staff_invites_delete_owner" on public.staff_invites for delete using (public.same_restaurant(restaurant_id) and public.has_role(array['owner']));
create policy "restaurant_settings_select_owner" on public.restaurant_settings for select using (public.same_restaurant(restaurant_id) and public.has_role(array['owner']));
create policy "restaurant_settings_insert_owner" on public.restaurant_settings for insert with check (public.same_restaurant(restaurant_id) and public.has_role(array['owner']));
create policy "restaurant_settings_update_owner" on public.restaurant_settings for update using (public.same_restaurant(restaurant_id) and public.has_role(array['owner'])) with check (public.same_restaurant(restaurant_id) and public.has_role(array['owner']));
create policy "restaurant_settings_delete_owner" on public.restaurant_settings for delete using (public.same_restaurant(restaurant_id) and public.has_role(array['owner']));

insert into public.restaurants (id, name, slug, address, phone, currency, tax_rate) values ('11111111-1111-1111-1111-111111111111', 'TableStack Bistro', 'tablestack-bistro', '18 Riverwalk Lane, Brisbane QLD', '+61 7 5555 0142', '$', 10) on conflict (id) do nothing;
insert into public.restaurant_settings (restaurant_id, bill_prefix, receipt_footer, print_kitchen_copy) values ('11111111-1111-1111-1111-111111111111', 'TS', 'Thank you for dining with us.', true) on conflict (restaurant_id) do nothing;
insert into public.menu_categories (id, restaurant_id, name, sort_order) values ('aaaaaaaa-0000-0000-0000-000000000001', '11111111-1111-1111-1111-111111111111', 'Starters', 1), ('aaaaaaaa-0000-0000-0000-000000000002', '11111111-1111-1111-1111-111111111111', 'Mains', 2), ('aaaaaaaa-0000-0000-0000-000000000003', '11111111-1111-1111-1111-111111111111', 'Drinks', 3) on conflict (id) do nothing;
insert into public.menu_items (id, restaurant_id, category_id, name, description, price, is_active, prep_minutes) values ('bbbbbbbb-0000-0000-0000-000000000001', '11111111-1111-1111-1111-111111111111', 'aaaaaaaa-0000-0000-0000-000000000001', 'Chicken Wings Plate', 'Crispy wings, chilli glaze, ranch.', 18, true, 9), ('bbbbbbbb-0000-0000-0000-000000000002', '11111111-1111-1111-1111-111111111111', 'aaaaaaaa-0000-0000-0000-000000000002', 'Smash Burger', 'Double patty, cheddar, pickles, house sauce.', 22, true, 12), ('bbbbbbbb-0000-0000-0000-000000000003', '11111111-1111-1111-1111-111111111111', 'aaaaaaaa-0000-0000-0000-000000000002', 'Green Market Salad', 'Leaves, avocado, tomato, lemon dressing.', 16, true, 6), ('bbbbbbbb-0000-0000-0000-000000000004', '11111111-1111-1111-1111-111111111111', 'aaaaaaaa-0000-0000-0000-000000000003', 'House Cola', '330ml bottle.', 5, true, 1) on conflict (id) do nothing;
insert into public.inventory_items (id, restaurant_id, name, unit, quantity_on_hand, reorder_level, cost_per_unit) values ('cccccccc-0000-0000-0000-000000000001', '11111111-1111-1111-1111-111111111111', 'Chicken wing pieces', 'piece', 220, 60, 0.72), ('cccccccc-0000-0000-0000-000000000002', '11111111-1111-1111-1111-111111111111', 'Burger buns', 'piece', 80, 24, 0.55), ('cccccccc-0000-0000-0000-000000000003', '11111111-1111-1111-1111-111111111111', 'Beef patties', 'piece', 130, 40, 1.85), ('cccccccc-0000-0000-0000-000000000004', '11111111-1111-1111-1111-111111111111', 'Mixed leaves', 'kg', 14, 5, 8.40), ('cccccccc-0000-0000-0000-000000000005', '11111111-1111-1111-1111-111111111111', 'House cola bottle', 'bottle', 96, 30, 1.15) on conflict (id) do nothing;
insert into public.menu_item_ingredients (restaurant_id, menu_item_id, inventory_item_id, quantity, unit) values ('11111111-1111-1111-1111-111111111111', 'bbbbbbbb-0000-0000-0000-000000000001', 'cccccccc-0000-0000-0000-000000000001', 5, 'piece'), ('11111111-1111-1111-1111-111111111111', 'bbbbbbbb-0000-0000-0000-000000000002', 'cccccccc-0000-0000-0000-000000000002', 1, 'piece'), ('11111111-1111-1111-1111-111111111111', 'bbbbbbbb-0000-0000-0000-000000000002', 'cccccccc-0000-0000-0000-000000000003', 2, 'piece'), ('11111111-1111-1111-1111-111111111111', 'bbbbbbbb-0000-0000-0000-000000000003', 'cccccccc-0000-0000-0000-000000000004', 0.18, 'kg'), ('11111111-1111-1111-1111-111111111111', 'bbbbbbbb-0000-0000-0000-000000000004', 'cccccccc-0000-0000-0000-000000000005', 1, 'bottle') on conflict (restaurant_id, menu_item_id, inventory_item_id) do nothing;
